sudo: required
services:
  - docker

  before_install:
    - docker build -t santhosh/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true santhosh/react-test npm test

after_success:
  - docker build -t santhosh/multi-client ./client
  - docker build -t santhosh/multi-nginx ./nginx
  - docker build -t santhosh/multi-server ./server
  - docker build -t santhosh/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push santhosh/multi-client 
  - docker santhosh/multi-nginx 
  - docker santhosh/multi-server 
  - docker santhosh/multi-worker
  